# Generated by Django 3.2.12 on 2024-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_tache_techniciens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titreTache',
            field=models.CharField(max_length=150),
        ),
    ]
