# Generated by Django 3.2.12 on 2024-03-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20240328_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='nomTechn',
            new_name='technicien',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='titreTache',
            new_name='titre',
        ),
    ]
