# Generated by Django 3.2.12 on 2024-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20240328_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='technicien',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techniciens',
            name='salaire',
            field=models.IntegerField(),
        ),
    ]
