# Generated by Django 3.2.12 on 2024-03-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20240328_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('membres', models.CharField(max_length=100)),
                ('datedebit', models.DateField()),
                ('datefin', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('commentaire', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='techniciens',
            name='dateembauch',
            field=models.DateField(),
        ),
    ]
