# Generated by Django 3.2.12 on 2024-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20240329_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproduit', models.CharField(max_length=100)),
                ('qualite', models.CharField(max_length=100)),
                ('dateinscri', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproduit', models.CharField(max_length=100)),
                ('datecreation', models.DateField()),
                ('dateexp', models.DateField()),
                ('dateentree', models.DateTimeField()),
                ('lots', models.CharField(max_length=100)),
                ('pu', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('pt', models.IntegerField()),
                ('commentaire', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='commentaire',
        ),
    ]
