# Generated by Django 3.2.12 on 2024-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20240405_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='qualite',
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
