# Generated by Django 3.2.12 on 2024-04-09 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0011_auto_20240409_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='technicien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.techniciens'),
        ),
    ]
