# Generated by Django 3.2.12 on 2024-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20240414_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='commentaire',
            field=models.CharField(max_length=100),
        ),
    ]
